version: '3.8'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  rcli:
    image: redis
    links:
      - redis
    command: redis-cli -h redis
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'database_development'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: 'passwd'
      MYSQL_ROOT_PASSWORD: 'passwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
